### PR TITLE
Support for building with webpack with AoT compilation

### PR DESCRIPTION
**Pull request by sis0k0**
A few changes were required:
- Dynamic router configuration is replaced by a static one;
- Some method calls in the components' templates weren't matching the signatures of the methods, defined in the components' classes;
- Codelyzer is updated to be compliant with Angular ~4 and tslint ~5
- Dynamic imports are replaced

Known issues:
- Problems with building for android (ping @Pip3r4o)
- Problems with components that use android/ios specific stylesheets (`ListviewItemSelectionMultipleComponent`, `ListviewItemSelectionProgrammaticComponent`, `ListviewObservableArrayComponent`)

### CODE REVIEW

**Comment by VladimirAmiorkov** [comment]
Resolved : 
Known issues:

- Problems with building for android (ping @Pip3r4o) - **_Was not able to reproduce this, works well on Android_** 
- Problems with components that use android/ios specific stylesheets (ListviewItemSelectionMultipleComponent, ListviewItemSelectionProgrammaticComponent, ListviewObservableArrayComponent) - **_Resolved issues_**

**Comment by Pip3r4o** [comment]
@VladimirAmiorkov @sis0k0 I was not able to reproduce the problem locally when bundling from the `vlaeva/aot` branch. I'll need a bit more time to verify there isn't an actual stopper when making bundles.

**Comment by VladimirAmiorkov** [comment]
@Pip3r4o Ok, you can go ahead and use the "rc" branch. That is the branch that is also currently being tested by our QAs

**Comment by Pip3r4o** [comment]
@VladimirAmiorkov @sis0k0 I managed to get it to break during bindings-generation on build. Fortunately I started working on a fix yesterday with assumptions as to the problem's nature. A character wasn't replaced properly in our generator's implementation, and would fail in rare cases.

Fix available in PR https://github.com/NativeScript/android-runtime/pull/754

QAs: to test locally download the runtime package from the Jenkins PR job.

**Pull request merged**
